spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${NEON_HOST}/${NEON_DB}?sslmode=require
    username: ${NEON_USER}
    password: ${NEON_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

trc:
  url: ${TRC_URL}
  email: ${TRC_EMAIL}
  password: ${TRC_PASSWORD}

cfobras:
  url: ${CFOBRAS_URL}
  email: ${CFOBRAS_EMAIL}
  password: ${CFOBRAS_PASSWORD}

automacao:
  download-dir: downloads
  obras:
    - codigo: SUPREME-ANALIA-FRANCO
      nome-trc: "Cury SP Supreme Analia Franco CCISA 183"
      nomes-cf-obras:
        - "SUPREME ANÁLIA FRANCO"
    - codigo: NOVO-MUNDO-CARRAO
      nome-trc: "Cury SP Novo Mundo Carrão CCISA188"
      nomes-cf-obras:
        - "NOVO MUNDO CARRÃO"
        - "NOVO MUNDO CARRÃO II"
    - codigo: ELO-SANTO-ANDRE
      nome-trc: "Cury SP Elo Santo Andre"
      nomes-cf-obras:
        - "ELO SANTO ANDRÉ"
    - codigo: MODERN-MOOCA
      nome-trc: "Cury SP Modern Mooca CCISA124"
      nomes-cf-obras:
        - "MODERN MOOCA"